### ISSUE TITLE
ESLint v9 support

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/bod#1175]
### Validations

- [X] Read the contributing guidelines.
- [X] Follow our code of conduct.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub discussion.

### Describe the Bug

Missing ESLint v9 support.

### Reproduction

```bash
pnpm add -D eslint@latest
pnpm lint
```

### Minimal Example

- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Expected Behavior

Linter works fine.

### System Information

```bash
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.15.6 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
```

### Used Package Manager

pnpm

#### Upstream

- [x] [eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react/issues/3699)
- [ ] [eslint-plugin-react-hooks](https://github.com/facebook/react/issues/28313)
- [ ] [eslint-plugin-jsx-a11y](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/978)
- [x] [eslint-plugin-promise](https://github.com/eslint-community/eslint-plugin-promise/issues/449)
- [x] [eslint-plugin-security](https://github.com/eslint-community/eslint-plugin-security/issues/144)
- [ ] [eslint-config-next](https://github.com/vercel/next.js/issues/64114)

#### Downstream

- [ ] [dblp](https://github.com/sabertazimi/dblp/pull/535)
- [ ] [hust-web](https://github.com/sabertazimi/hust-web/pull/1043)
- [ ] [OJs](https://github.com/sabertazimi/OJs/pull/354)
- [ ] [awesome-web](https://github.com/sabertazimi/awesome-web/pull/646)
- [ ] [awesome-notes](https://github.com/sabertazimi/awesome-notes/pull/528)
- [ ] [blog](https://github.com/sabertazimi/blog/pull/1278)
- [ ] [bod](https://github.com/sabertazimi/bod/pull/1203)

**Comment by sabertazimi** [comment]
- [ ] [eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react/issues/3699)
- [ ] [eslint-plugin-react-hooks](https://github.com/facebook/react/issues/28313)
- [ ] [eslint-plugin-security](https://github.com/eslint-community/eslint-plugin-security/issues/144)
- [ ] [eslint-config-next](https://github.com/vercel/next.js/issues/64114)
